---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: wacky-tracky
builds:
  - id: wacky-tracky
    dir: service
    main: main.go
    binary: wacky-tracky-server
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - >
        -s -w
        -X 'github.com/wacky-tracky/wacky-tracky-server/internal/buildinfo.Commit={{.Commit}}'
        -X 'github.com/wacky-tracky/wacky-tracky-server/internal/buildinfo.BuildDate={{.Date}}'
        -X 'github.com/wacky-tracky/wacky-tracky-server/internal/buildinfo.Version={{.Version}}'

dockers_v2:
  - dockerfile: Dockerfile
    images:
      - ghcr.io/jamesread/wacky-tracky
    tags:
      - "{{ .Version }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    extra_files:
      - README.md
      - frontend/dist
    platforms:
      - linux/amd64
      - linux/arm64


checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Branch }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^cicd:'
      - '^refactor:'
  groups:
    - title: 'Security'
      regexp: '^.*?security(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Features'
      regexp: '^.*?feature(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug fixes'
      regexp: '^.*?bugfix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  footer: |
    ## Container images (from GitHub)

    - `docker pull ghcr.io/jamesread/wacky-tracky:{{ .Version }}`

    ## Upgrade warnings, or breaking changes

    - No such issues between the last release and this version.

    Thanks for your interest in WackyTracky!
