---
project_name: wacky-tracky-server
before:
  hooks:
    - go mod download
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux

    goarch:
      - amd64

    main: main.go

    ldflags:
      - >
        -s -w
        -X buildinfo.Version={{.Version}}
        -X buildinfo.Commit={{.ShortCommit}}
        -X buildinfo.Date={{ .CommitDate }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Branch }}-{{ .ShortCommit }}"
changelog:
  sort: asc
  groups:
    - title: 'Security'
      regexp: '^.*?security(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Features'
      regexp: '^.*?feature(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug fixes'
      regexp: '^.*?bugfix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^cicd:'
      - '^refactor:'

archives: []

dockers:
  - image_templates:
      - "ghcr.io/wacky-tracky/wacky-tracky-server:{{ .Tag }}-amd64"
      - "ghcr.io/wacky-tracky/wacky-tracky-server:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
      - frontend/dist

release:
  footer: |
    ## Container images (from GitHub)

    - `docker pull ghcr.io/wacky-tracky/wacky-tracky-server:{{ .Version }}`

    ## Upgrade warnings, or breaking changes

    - No such issues between the last release and this version.

    Thanks for your interest in wacky-tracky-server!
