name: tag

on:
  push:
    tags:
      - '*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'


      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: Build
        run: make -w grpc default webui
        env:
          GH_TOKEN: ${{ github.token }}

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

